theme_color:
  primary: indigo
  accent: pink

notice:

favicon: /images/favicon.ico
banner: /images/Whitebeard's_silhouette.png
avatar: /images/avator.png
# rss: /atom.xml

email: zh_cn2008@hotmail.com
sns:
  twitter:
  facebook:
  google_plus:
  weibo: https://weibo.com/u/2867090703
  instagram:
  tumblr:
  github: https://github.com/ZXS66
  linkedin:
  zhihu:
  douban:
  qq: https://user.qzone.qq.com/546990481
  wechat: /static/qrcode.html?data=https%3A%2F%2Fu.wechat.com%2FENx87m7_oPP-mj2Ur-ffHIY

open_graph:
  twitter:
  google_plus:
  fb_admins:
  fb_app_id:
site_verification:
  google:
  baidu:
analytics:
  google_site_id:
  baidu_site_id:
  cnzz_site_id:

pages:
# - name: 时间轴
#   link: /timeline
- name: 标签云
  link: /tagcloud
# - name: 相册
#   link: /gallery
links:
- name: My Github
  link: https://github.com/ZXS66
- name: This Theme
  link: https://niemingzhao.github.io/

since:
footer_text:
license:

gallery:
  fancybox_css: //cdn.bootcdn.net/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css
  fancybox_js: //cdn.bootcdn.net/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js
  jquery_js: //cdn.bootcdn.net/ajax/libs/jquery/3.3.1/jquery.min.js
  lazyload_js: //cdn.bootcdn.net/ajax/libs/jquery_lazyload/1.9.7/jquery.lazyload.min.js
donate:
search:
  placeholder: 请输入关键字
  use: plugin
comment:
  use: false
  disqus_shortname:
  gitalk_client_id:
  gitalk_client_secret:
  gitalk_repo:
  gitalk_owner:
  gitalk_sid_type:
  livere_data_uid:
  valine_leancloud_app_id:
  valine_leancloud_app_key:
  valine_placeholder:
  valine_page_size:
  valine_avatar:
  valine_lang:
  valine_guest_info:
  valine_notify:
  valine_verify:
  valine_sid_type:
  changyan_app_id:
  changyan_app_key:
  changyan_sid_type:

app: /../ng